- docs/modules/ROOT/pages/data-encryption.adoc
- docs/modules/ROOT/pages/data-profiling-details.adoc
- docs/modules/ROOT/pages/data-validation.adoc
- docs/modules/ROOT/pages/drift-detection.adoc
- docs/modules/ROOT/pages/file-storage-details.adoc
- docs/modules/ROOT/pages/pyspark-data-delivery-pipeline-details.adoc
- docs/modules/ROOT/pages/spark-data-delivery-pipeline.adoc
Tranche 5
[Spark Data Delivery Pipelines](https://boozallen.github.io/aissemble/aissemble/current/spark-data-delivery-pipeline.html)
[PySpark Data Delivery Pipelines](https://boozallen.github.io/aissemble/aissemble/current/pyspark-data-delivery-pipeline-details.html)
[Data Encryption](https://boozallen.github.io/aissemble/aissemble/current/data-encryption.html)
[Data Profiling](https://boozallen.github.io/aissemble/aissemble/current/data-profiling-details.html)
[Data Validation](https://boozallen.github.io/aissemble/aissemble/current/data-validation.html)
[Drift Detection](https://boozallen.github.io/aissemble/aissemble/current/drift-detection.html)
[File Storage](https://boozallen.github.io/aissemble/aissemble/current/file-storage-details.html)
> #5 :memo: Tranche 5 of documentation migration

- DRAFT_RELEASE_NOTES.md
- foundation/foundation-mda/src/main/resources/templates/notifications/notification.deploy.clean.app.target.vm
Update the release notes with the breaking change
closes #22
>  #22 Removed maven-clean-plugin version from pom generation

- extensions/extensions-docker/aissemble-model-training-api-containers/aissemble-model-training-api-sagemaker/src/main/resources/docker/Dockerfile
- extensions/extensions-docker/aissemble-model-training-api-containers/aissemble-model-training-api/src/main/resources/docker/Dockerfile
- extensions/extensions-docker/aissemble-versioning/src/main/resources/docker/Dockerfile
- foundation/foundation-configuration-store/src/main/java/com/boozallen/aissemble/configuration/store/YamlProperty.java
- foundation/foundation-mda/src/main/resources/templates/general-docker/airflow.docker.file.vm
- foundation/foundation-mda/src/main/resources/templates/general-docker/inference.docker.file.vm
- foundation/foundation-mda/src/main/resources/templates/general-docker/sagemaker-training.docker.file.vm
- foundation/foundation-mda/src/main/resources/templates/general-docker/spark-worker.docker.file.vm
- foundation/foundation-mda/src/main/resources/templates/general-docker/training.docker.file.vm
- foundation/foundation-upgrade/src/main/java/com/boozallen/aissemble/upgrade/migration/v1_7_0/DockerPipInstallMigration.java
- foundation/foundation-upgrade/src/main/java/com/boozallen/aissemble/upgrade/util/FileUtils.java
- foundation/foundation-upgrade/src/main/resources/migrations.json
- foundation/foundation-upgrade/src/test/java/com/boozallen/aissemble/upgrade/migration/v1_7_0/DockerPipInstallMigrationSteps.java
- foundation/foundation-upgrade/src/test/resources/specifications/v1_7_0/docker-pip-install-migration.feature
- foundation/foundation-upgrade/src/test/resources/test-files/v1_7_0/DockerPipInstallMigration/migration/dockerfile
- foundation/foundation-upgrade/src/test/resources/test-files/v1_7_0/DockerPipInstallMigration/skip-migration/dockerfile
- foundation/foundation-upgrade/src/test/resources/test-files/v1_7_0/DockerPipInstallMigration/validation/dockerfile
- updated relevant source docker files in `extensions-docker` that we manage in the baseline to implement "fail fast" behavior with installing python dependencies
- updated templates accordingly
- added migration to update downstream dockerfiles
> #8 Require docker builds to fail if Python installation fails + migration

- .github/workflows/build.yml
- build-parent/pom.xml
- extensions/extensions-docker/aissemble-airflow/pom.xml
- extensions/extensions-docker/aissemble-airflow/src/main/resources/docker/Dockerfile
- extensions/extensions-docker/aissemble-jenkins/aissemble-jenkins-controller/pom.xml
- extensions/extensions-docker/aissemble-jenkins/aissemble-jenkins-controller/src/main/resources/docker/Dockerfile
- extensions/extensions-docker/aissemble-nvidia/pom.xml
- extensions/extensions-docker/aissemble-nvidia/src/main/resources/docker/Dockerfile
- extensions/extensions-docker/aissemble-spark-infrastructure/pom.xml
- extensions/extensions-docker/aissemble-spark-infrastructure/src/main/resources/docker/Dockerfile
- extensions/extensions-docker/aissemble-spark/pom.xml
- extensions/extensions-docker/aissemble-spark/src/main/resources/docker/Dockerfile
- extensions/extensions-docker/pom.xml
- extensions/extensions-helm/pom.xml
- foundation/foundation-archetype/src/main/resources/archetype-resources/pom.xml
- pom.xml
There will be a follow on to this PR to handle certain build issues such as the limited amount of disk space on the Action Runner.
> #2 Add Github Action build workflow

- extensions/aissemble-extensions-model-training-api-sagemaker/pyproject.toml
Resolves CVE-2024-34072 and CVE-2024-34073 by upgrading SageMaker to >= 2.218.0.  There was previously an upper cap on the version that was ostensibly for Python 3.11.4 compatibility, but it looks like 2.218 supports Python 3.11.4.
> Resolve SageMaker CVEs

- .gitignore
- build-parent/pom.xml
- extensions/extensions-docker/aissemble-kafka/src/main/resources/docker/Dockerfile
- extensions/extensions-helm/aissemble-airflow-chart/pom.xml
- extensions/extensions-helm/aissemble-jenkins-chart/pom.xml
- extensions/extensions-helm/aissemble-kafka-chart/Chart.yaml
- extensions/extensions-helm/aissemble-kafka-chart/pom.xml
- extensions/extensions-helm/aissemble-kafka-chart/values.template.yaml
- extensions/extensions-helm/aissemble-mlflow-chart/pom.xml
- extensions/extensions-helm/aissemble-spark-operator-chart/pom.xml
- extensions/extensions-helm/pom.xml
- foundation/foundation-maven-plugins/artifacts-maven-plugin/pom.xml
- foundation/foundation-maven-plugins/mda-maven-plugin/pom.xml
- pom.xml
Updates the base image for the aissemble-kafka image from wurstmeister kafka to bitnami/kafka:3.5.  The bitnami image was selected because our helm chart, aissemble-kafka-chart, is based on the bitnami kafka chart. The version 3.5 was chosen over the newer 3.7 version image because there was a major refactor to bitnami's chart in chart version 24.0 that would have required a significant refactor and testing to our chart to upgrade beyond. Instead I updated to the last compatible version of the chart, 23.0.7, which was based on the 3.5 image.
> #51 update kafka base image to bitnami

- DRAFT_RELEASE_NOTES.md
- docs/modules/ROOT/pages/archetype.adoc
- foundation/foundation-archetype/src/main/resources/META-INF/maven/archetype-metadata.xml
- foundation/foundation-archetype/src/main/resources/archetype-resources/pom.xml
Added functionality to set maven publishing repos (releases and snapshots) in downstream projects of aissemble.
- Publishing repo urls were added as `requiredProperties`. They can either be updated in the project creation (by selecting "n" when confirming and overriding the defaults) or by updating them in the `<properties>` section of the root pom in the downstream project.
- Updated docs with `mavenPublishingRepoUrl` and `mavenSnapshotPublishingRepoUrl` fields
> 49-downstream-maven-publishing-repo

- DRAFT_RELEASE_NOTES.md
- test/test-mda-models/aissemble-test-data-delivery-pyspark-model-basic/pom.xml
- test/test-mda-models/aissemble-test-data-delivery-pyspark-model/pom.xml
Updating dependencies in the test-mda-models pyspark POMs to match what would be generated today by `foundation-mda`, so the generated code more is more directly tested as it would be in a downstream project.
> #72 resync test pyspark poms

- DRAFT_RELEASE_NOTES.md
- docs/modules/ROOT/pages/archetype.adoc
- foundation/foundation-archetype/src/main/resources/META-INF/maven/archetype-metadata.xml
- foundation/foundation-archetype/src/main/resources/archetype-resources/__rootArtifactId__-deploy/pom.xml
- foundation/foundation-archetype/src/main/resources/archetype-resources/pom.xml
- allow downstream users to set helm publishing repo name and URL during project creation
- update documentation and release notes
>  #84 Set Helm publishing repo for downstream projects

- SECURITY.md
We enabled the ability to create security advisories for the reporting of vulnerabilities on the project. This required an update to the security.md file to direct folks to the correct link for reporting a potential vulnerability as well as some minor verbiage updates.
> 104-Update-SECURITY.md

- build-parent/pom.xml
- extensions/extensions-configuration-store-vault/pom.xml
- extensions/extensions-configuration-store-vault/src/main/resources/META-INF/beans.xml
- extensions/extensions-configuration-store-vault/src/main/resources/quarkus-app.xml
- extensions/extensions-data-lineage/extensions-data-lineage-http-consumer-service/pom.xml
- extensions/extensions-pipeline-invocation-service/pom.xml
- foundation/foundation-configuration-store/pom.xml
- foundation/foundation-configuration-store/src/main/resources/META-INF/beans.xml
- foundation/foundation-configuration-store/src/test/java/CucumberTest.java
> #108 vault property dao class can be injected when use the extensions-configuration-store-vault module

- DRAFT_RELEASE_NOTES.md
- foundation/foundation-mda/src/main/resources/templates/deployment/argocd/v2/sealed.secret.yaml.vm
- foundation/foundation-upgrade/src/main/java/com/boozallen/aissemble/upgrade/migration/v1_7_0/SparkAppExecMigration.java
- foundation/foundation-upgrade/src/test/java/com/boozallen/aissemble/upgrade/migration/v1_7_0/SparkAppExecMigrationSteps.java
- foundation/foundation-upgrade/src/test/resources/specifications/v1_7_0/spark-application-exec-migration.feature
- foundation/foundation-upgrade/src/test/resources/test-files/v1_7_0/SparkAppExecMigration/migration/tests-pom.xml
~Now that downstream projects have the build cache enabled by default, our archetype test isn't always catching and testing new changes to the underlying dependencies. In this case, the baton migrations were cached and so were skipped, giving the impression that the new migration was functioning correctly when it just hadn't been tested. To fix this, the test script has been updated to disable the build cache for the final build of the archetype test.~
> #123 Fix NPE when running in Tests module

- foundation/aissemble-foundation-core-python/src/policy_manager/policy/policy.py
Resolved pylint error:
```
[INFO] ************* Module policy_manager.policy.policy
[INFO] src/policy_manager/policy/policy.py:86:17: E1101: Class 'BaseConfig' has no 'property_set_methods' member (no-member)
[INFO] src/policy_manager/policy/policy.py:146:17: E1101: Class 'BaseConfig' has no 'property_set_methods' member (no-member)
```
> #118 Store map of deprecated methods on class instead of Pydantic config

- foundation/foundation-mda/src/main/resources/templates/data-delivery-pyspark/encryption.py.vm
Fixing the failed aissemble-test-data-delivery-pyspark-model module, was not able to find a python function which was renamed to aissemble.
> #122 Refactoring the Foundation Core Python module; removing aiops references (Part 2).

- DRAFT_RELEASE_NOTES.md
- foundation/foundation-data-access/src/main/java/com/boozallen/aissemble/data/access/AbstractDataAccessRecord.java
- foundation/foundation-data-access/src/main/java/com/boozallen/aissemble/data/access/DataAccessWhereClause.java
- foundation/foundation-data-access/src/main/java/com/boozallen/aissemble/data/access/DataAccessWhereOperator.java
- foundation/foundation-data-access/src/main/java/com/boozallen/aissemble/data/access/QueryService.java
- foundation/foundation-data-access/src/main/java/com/boozallen/aissemble/data/access/SparkQueryService.java
- foundation/foundation-data-access/src/main/java/com/boozallen/aissemble/data/access/config/DataAccessConfig.java
- foundation/foundation-data-access/src/main/java/com/boozallen/aissemble/data/access/security/DataAccessRolesAugmentor.java
- foundation/foundation-data-access/src/main/resources/META-INF/beans.xml
- foundation/foundation-data-access/src/main/resources/application.properties
- foundation/foundation-mda/src/main/resources/templates/data-access/data.access.record.base.java.vm
- foundation/foundation-mda/src/main/resources/templates/data-access/data.access.resource.base.java.vm
- foundation/foundation-upgrade/src/main/java/com/boozallen/aissemble/upgrade/migration/v1_8_0/AiopsReferenceJavaMigration.java
- foundation/foundation-upgrade/src/main/resources/migrations.json
- foundation/foundation-upgrade/src/test/java/com/boozallen/aissemble/upgrade/migration/v1_8_0/AiopsReferenceJavaMigrationSteps.java
- foundation/foundation-upgrade/src/test/resources/specifications/v1_8_0/aiops-reference-java-migration.feature
- foundation/foundation-upgrade/src/test/resources/test-files/v1_8_0/AiopsReferenceJavaMigration/migration/DataAccessRecord.java
- foundation/foundation-upgrade/src/test/resources/test-files/v1_8_0/AiopsReferenceJavaMigration/validation/DataAccessRecordValidated.java
#183: Refactor Foundation Data Access module with latest aiSSEMBLE landscape:
- Refactor the Foundation Data Access module.
- `/foundation/foundation-data-access`
- Refactor all the child directories, classes, and methods.
- Corrected all the imports inside the velocity templates to ensure a successful build Foundation Data Access.
- Baton migration scripts for automated migrations from legacy package names to the new aiSSEMBLE landscape.
> #183: Refactor Foundation Data Access module with latest aiSSEMBLE landscape

- build-parent/pom.xml
- extensions/extensions-docker/aissemble-model-training-api-containers/aissemble-model-training-api-sagemaker/src/main/resources/docker/Dockerfile
- extensions/extensions-docker/aissemble-model-training-api-containers/aissemble-model-training-api/src/main/resources/docker/Dockerfile
- extensions/extensions-docker/aissemble-versioning/src/main/resources/docker/Dockerfile
- extensions/extensions-docker/pom.xml
Technically, the failures in CI were due to two issues:
- the one line change to the `Dockerfile` of `aissemble-fastapi` to use `python:3.11`
- a change to the builder image used by Habushu to `python:3.11`
- In order to support using `3.11-slim` for the final image, a new version of Habushu was released an pulled in (2.16.1)
However, while diagnosing this I found some oddities that made this hard to track down:
1. `docker buildx prune` only prunes the default builder, the same seems to be true of `system prune`.
2. changing the config directory of docker via `--config` changes what builders are visible, and what cache space they are using
3. by default, the `docker-maven-plugin` creates a builder named `maven` with a config directory pointing inside the `target` of the project 
Because …
> #150 revert fastapi image to `python:3.11` and re-use default docker cache

- extensions/extensions-docker/aissemble-fastapi/src/main/resources/docker/Dockerfile
Somehow reverted the oneline change to aissemble-fastapi without noticing in PR #196
> #150 switch fastapi image to python:3.11

- extensions/extensions-docker/aissemble-hive/aissemble-hive-service/pom.xml
- extensions/extensions-docker/aissemble-hive/aissemble-hive-service/src/main/resources/docker/Dockerfile
- extensions/extensions-docker/aissemble-spark-infrastructure/pom.xml
- extensions/extensions-docker/aissemble-spark-infrastructure/src/main/resources/docker/Dockerfile
- extensions/extensions-docker/aissemble-spark/src/main/resources/docker/Dockerfile
We use curly braces for some of the ENV substitutions in our Dockerfiles, but because fabric8 does Maven property expansion, and by default looks for ${} to do that substitution, we were getting injection of host machine values instead of properly using the VM’s env. This PR is to change the environment variable substitution from ${X} to $X
> #199 fix environment variable substitution issue

- .github/workflows/build.yml
- extensions/extensions-docker/pom.xml
Docker Hub has a rate limit and we have been running into the the`429 Too Many Requests ` issue. This fix is to make sure that fabric8 uses the registry mirror by passing the toml configuration file when creating docker builder.
> #199 fix CI too many requests issue

- .gitignore
- extensions/extensions-helm/extensions-helm-pipeline-invocation/aissemble-pipeline-invocation-app-chart/.helmignore
- extensions/extensions-helm/extensions-helm-pipeline-invocation/aissemble-pipeline-invocation-app-chart/pom.xml
- extensions/extensions-helm/extensions-helm-pipeline-invocation/aissemble-pipeline-invocation-app-chart/values.template.yaml
- foundation/foundation-mda/src/main/resources/templates/deployment/pipeline-invocation-service/v2/pipeline.invocation.service.values-dev.yaml.vm
- foundation/foundation-mda/src/main/resources/templates/deployment/pipeline-invocation-service/v2/pipeline.invocation.service.values.yaml.vm
Aligns `aissemble-pipeline-invocation-chart-app` with best practices by:
- Generating the correct image tag at build time instead of embedding in downstream chart
- Using LoadBalancer to expose services for local testing
- Pulling common configs into the parent chart instead of embedding in downstream charts
- includes fixing the configuration of the Quarkus chart in the default values.yaml
>  #199 cleanup pipeline invocation service chart

- build-parent/pom.xml
- extensions/extensions-docker/aissemble-configuration-store/pom.xml
- extensions/extensions-docker/aissemble-configuration-store/src/main/resources/docker/Dockerfile
- extensions/extensions-docker/aissemble-data-lineage-http-consumer/pom.xml
- extensions/extensions-docker/aissemble-data-lineage-http-consumer/src/main/resources/docker/Dockerfile
- extensions/extensions-docker/aissemble-metadata/pom.xml
- extensions/extensions-docker/aissemble-metadata/src/main/resources/docker/Dockerfile
- extensions/extensions-docker/aissemble-pipeline-invocation/pom.xml
- extensions/extensions-docker/aissemble-pipeline-invocation/src/main/resources/docker/Dockerfile
- extensions/extensions-docker/aissemble-policy-decision-point/pom.xml
- extensions/extensions-docker/aissemble-policy-decision-point/src/main/resources/docker/Dockerfile
- extensions/extensions-docker/aissemble-quarkus/src/main/resources/docker/Dockerfile
- extensions/extensions-docker/aissemble-quarkus/src/main/resources/scripts/run-env.sh
Prior to transitioning the Quarkus-based Docker images off of the `aissemble-quarkus` image, we were setting JAVA_OPTIONS at startup via the `run-env.sh` script to include the Krausinening configuration through environment variables.  When it was moved, the script was dropped and the ENV vars were set directly during the image build. However, this makes the config unresponsive to the `env` config for Helm deployments which removes the ability to point Krausening to a different location at deploy time. For now, we'll just revert to using `aissemble-quarkus` and the `run-env.sh` script there.  Further work on Universal Config and a more "serverless" style of deployment will likely end up illuminating a better answer in the future.
> #199 fix Krausening/Quarkus config through helm

- extensions/extensions-encryption/aissemble-extensions-encryption-vault-python/tests/features/encryption.feature
- extensions/extensions-encryption/aissemble-extensions-encryption-vault-python/tests/features/environment.py
- extensions/extensions-encryption/aissemble-extensions-encryption-vault-python/tests/features/vault.feature
There is one unit test in `aissemble-extensions-encryption-vault-python` and 3 ITs. Because of the way the feature files and `environent.py` setup was structured, the Vault container was spun up even if only the unit test is being executed and the ITs are excluded.  This causes problems during the release as the Vault container is not available during the preparation phase, and generally slows down builds.
> #199 only start Vault during ITs

- build-parent/pom.xml
- extensions/extensions-docker/aissemble-configuration-store/src/main/resources/docker/Dockerfile
- extensions/extensions-docker/aissemble-data-lineage-http-consumer/src/main/resources/docker/Dockerfile
- extensions/extensions-docker/aissemble-metadata/src/main/resources/docker/Dockerfile
- extensions/extensions-docker/aissemble-pipeline-invocation/src/main/resources/docker/Dockerfile
- extensions/extensions-docker/aissemble-policy-decision-point/README.md
- extensions/extensions-docker/aissemble-policy-decision-point/src/main/resources/authorization/attributes/test-attributes.json
- extensions/extensions-docker/aissemble-policy-decision-point/src/main/resources/authorization/pdp.xml
- extensions/extensions-docker/aissemble-policy-decision-point/src/main/resources/authorization/policies/test-policy.xml
- extensions/extensions-docker/aissemble-policy-decision-point/src/main/resources/docker/Dockerfile
- extensions/extensions-docker/aissemble-spark/src/main/resources/conf/log4j.properties
- extensions/extensions-docker/aissemble-versioning/README.md
- extensions/extensions-docker/aissemble-versioning/src/main/resources/model_versioning/model-pom.xml
The rename of the security module in #232 broke the default Policy Decision Point image, because of the class rename of `AissembleAttributeExtension` was not propagated to the `pdp.xml` file. The demo/example policy was also broken because the subject/user name and the URN of the attribute that the `LocalAttributePoint` class was looking for was changed, but the test-attribute.json and test-policy.xml included in the image was not updated. Further, the example JWT token was for the wrong subject name.
>  #255 fix PDP image and change Dockerfile delimiter

- extensions/extensions-data-lineage/extensions-data-lineage-http-consumer-service/pom.xml
- extensions/extensions-docker/aissemble-policy-decision-point/pom.xml
- extensions/extensions-docker/aissemble-policy-decision-point/src/main/resources/docker/Dockerfile
- extensions/extensions-security/extensions-policy-decision-point-service/pom.xml
- extensions/extensions-security/extensions-policy-decision-point-service/src/main/resources/quarkus-app.xml
In the past we have packaged jar files using the uber-jar pattern. This has turned out to be problematic for downstream projects due to how plugin.xml is compiled. For this reason, we now package them into a zip file. policy-decision-point still use the old pattern and need to be migrated
Github issue:
https://github.com/boozallen/aissemble/issues/258
> #258 update policy-decision-point to package service into zip instead of uber-jar

- extensions/extensions-helm/aissemble-spark-operator-chart/README.md
- extensions/extensions-helm/aissemble-spark-operator-chart/templates/rbac.yaml
- extensions/extensions-helm/aissemble-spark-operator-chart/values.template.yaml
Found the previous rbac.yaml file we were using to define access for reasources and just copied over that. Currently, we were using the community spark-operator rbac.yaml which didnt allow write access for the apiextensions.k8s.io apigroup.
> Grant spark-operator write access for the required apigroup

- DRAFT_RELEASE_NOTES.md
- extensions/extensions-helm/aissemble-mlflow-chart/Chart.yaml
- extensions/extensions-helm/aissemble-mlflow-chart/README.md
- extensions/extensions-helm/aissemble-mlflow-chart/values.yaml
- foundation/foundation-upgrade/src/main/java/com/boozallen/aissemble/upgrade/migration/v1_9_0/MLFlowDockerfileMigration.java
- foundation/foundation-upgrade/src/test/java/com/boozallen/aissemble/upgrade/migration/v1_9_0/MLFlowDockerfileMigrationSteps.java
- foundation/foundation-upgrade/src/test/resources/specifications/v1_9_0/ml-flow-dockerfile-migration.feature
- foundation/foundation-upgrade/src/test/resources/test-files/v1_9_0/MLFlowDockerfileMigration/migration/Dockerfile
- foundation/foundation-upgrade/src/test/resources/test-files/v1_9_0/MLFlowDockerfileMigration/validation/Dockerfile
#226 Replace aissemble-mflow docker image with community docker image.
- Replacing aissemble-mlflow with community docker image from bitnami. 
- Upgrade mlflow to the latest stable version.
> #226 Replace aissemble-mflow docker image with community docker image.

- DRAFT_RELEASE_NOTES.md
- foundation/foundation-upgrade/src/main/resources/migrations.json
#226 Replace aissemble-mflow docker image with community docker image (continued).
- Added MLFlow docker migration to Automatic Upgrades table in Release notes. 
- Added mlflow migration to migrations.json.
> #226 Replace aissemble-mflow docker image with community docker image (continued)

- .github/workflows/prune.yml
- Update prune workflow to use `dataaxiom/ghcr-cleanup-action@v1`
- Pass in all aiSSEMBLE docker image names through a matrix
- Pass in list of release versions to the `exclude-tags` parameter (e.g., `1.7.0,1.8.0`)
- Use `keep-n-tagged: 2` to ensure that the two most recent NON-release tagged images are saved (e.g., `1.9.0-SNAPSHOT` & `1.8.0-rc8`)
>  #270 Adjust prune workflow

- .github/workflows/prune.yml
This is to remove any rows that are blank from the `all_release_versions` array before saving them to output. Without this added logic, if we have any docker images that do not have any release versions, the `exclude-tags` parameter gets set to `,1.7.0,1.8.0` (with an extra comma at the front).
> #270-2 Fix to remove empty values from release_values

- .github/workflows/build.yml
The current build does not execute archetype tests. We would like to configure the build so that archetype tests are ran as part of the build process.
> #295 - Adding archetype tests to github build actions

- DRAFT_RELEASE_NOTES.md
- extensions/extensions-helm/aissemble-airflow-chart/Chart.yaml
- extensions/extensions-helm/aissemble-airflow-chart/README.md
- extensions/extensions-helm/aissemble-airflow-chart/values.yaml
- foundation/foundation-upgrade/src/main/java/com/boozallen/aissemble/upgrade/migration/v1_9_0/AirflowDockerfileMigration.java
- foundation/foundation-upgrade/src/main/resources/migrations.json
- foundation/foundation-upgrade/src/test/java/com/boozallen/aissemble/upgrade/migration/AbstractMigrationTest.java
- foundation/foundation-upgrade/src/test/java/com/boozallen/aissemble/upgrade/migration/v1_9_0/AirflowDockerfileMigrationSteps.java
- foundation/foundation-upgrade/src/test/java/com/boozallen/aissemble/upgrade/migration/v1_9_0/MLFlowDockerfileMigrationSteps.java
- foundation/foundation-upgrade/src/test/resources/specifications/v1_9_0/airflow-dockerfile-migration.feature
- foundation/foundation-upgrade/src/test/resources/test-files/v1_9_0/AirflowDockerfileMigration/migration/Dockerfile
- foundation/foundation-upgrade/src/test/resources/test-files/v1_9_0/AirflowDockerfileMigration/migration/negative-Dockerfile
- foundation/foundation-upgrade/src/test/resources/test-files/v1_9_0/AirflowDockerfileMigration/migration/negative-non-Airflow-Dockerfile
- foundation/foundation-upgrade/src/test/resources/test-files/v1_9_0/AirflowDockerfileMigration/validation/Dockerfile
- foundation/foundation-upgrade/src/test/resources/test-files/v1_9_0/AirflowDockerfileMigration/validation/negative-Dockerfile
#227 Replace aissemble-airflow docker image with community docker image.
- Airflow will now be pulling from the community Docker image. '
- Airflow helm chart upgraded from 1.10.0 to 1.15.0. 
- Migration script for switching aissemble-airflow to community Airflow Docker image.
> #227 - Replacing aissemble-airflow docker image with community airflow docker image.

- .github/actions/install_dependencies/action.yaml
- .github/actions/split_version/action.yaml
- .github/actions/update_antora/action.yaml
- .github/workflows/release.yml
This is a PR to add the aiSSEMBLE GitHub Action release job. This action mimics the Jenkins release job found here https://github.boozallencsn.com/aissemble/aissemble/blob/fix-ci/devops/JenkinsfileRelease.groovy
The release job aims to do the following
- Parses the inputted version to get its major, minor, and patch counterparts
- Executes a pre release update to the release branch's Antora documentation 
- Cuts a release of the release branch
- Executes a post release update to the release branch's Antora documentation
> #3 Added aiSSEMBLE GitHub Action release job

- DRAFT_RELEASE_NOTES.md
- extensions/extensions-helm/aissemble-kafka-chart/values.yaml
- foundation/foundation-mda/src/main/resources/templates/deployment/kafka/kafka.values.yaml.vm
#228 Replace aissemble-kafka docker image with community docker image.
- Updated Kafka helm chart to pull the community Docker image from Apache.
-  Upgraded Kafka Docker image from `3.5.1` to `3.8.0`.
- Updated Kafka Helm chart from `23.0.7` to `30.1.1`.
> #228 - Replace aissemble-kafka 1.7.0 references with community docker image

- foundation/aissemble-foundation-model-training-api/src/model_training_api/model_training_api.py
This PR is to fix issue https://github.com/boozallen/aissemble/issues/147
Description:
The Model Training API [documentation](https://boozallen.github.io/aissemble/aissemble/current/machine-learning-pipeline-details.html#_model_training_api) says to submit a DELETE HTTP call to remove a model training job. However, doing so results in a 403: Method Not Allowed response.
> #147 BUG: Fix Delete Model Training API in aiSSEMBLE

- foundation/foundation-mda/src/main/java/com/boozallen/aiops/mda/generator/AbstractKubernetesGenerator.java
The Configuration Store requires special logic to be deployed properly via Tilt.  When deciding on where the MVP should be and weighing the options against our planned move _away_ from Tilt, we decided it was best to just exclude the configuration store from local deployments for now and provide projects with instructions upon request.  However, in doing that we accidentally routed the config store to the standard Tilt manual action notification, which doesn't work at all.
This change correctly supresses the Tilt manual action if it is for the config store.  Note that the only real way to ensure this check was to use the `appName`, which technically could be changed by a downstream project which would result in the manual action reappearing.  This is an edge case, and again the plan is to …
> [#370] only show Tilt notification if not config-store

- foundation/foundation-mda/src/main/resources/templates/data-delivery-data-records/combined.pyproject.toml.vm
- foundation/foundation-mda/src/main/resources/templates/data-delivery-data-records/separate.core.pyproject.toml.vm
- foundation/foundation-mda/src/main/resources/templates/data-delivery-data-records/separate.spark.pyproject.toml.vm
We updated the version bound for python to be `>=3.8` in a previous commit, but missed updating the MDA templates for data record modules. This resulted in a failure to build projects with data records, as the version range `^3.11.4` was no longer satisfied when installing the dependencies of a PySpark pipeline.
> [#366] fix data record python version

- foundation/foundation-mda/src/main/java/com/boozallen/aiops/mda/metamodel/element/java/JavaStepDataRecordType.java
When the package name of a record matches the package name of a Spark data pipeline, the record cannot be used as an inbound or outbound record type because a NPE is thrown.
[Issue #152 ](https://github.com/boozallen/aissemble/issues/152)
> #152 Records with the same package as a data pipeline cannot be used as inbound/outbound types

- build-parent/pom.xml
- extensions/extensions-docker/aissemble-fastapi/src/main/resources/docker/Dockerfile
- extensions/extensions-docker/aissemble-hive-service/src/main/resources/docker/Dockerfile
- extensions/extensions-docker/aissemble-jenkins/aissemble-jenkins-agent/src/main/resources/docker/Dockerfile
- extensions/extensions-docker/aissemble-jenkins/aissemble-jenkins-controller/src/main/resources/docker/Dockerfile
- extensions/extensions-docker/aissemble-nvidia/src/main/resources/docker/Dockerfile
- extensions/extensions-docker/aissemble-spark-operator/src/main/resources/docker/Dockerfile
- extensions/extensions-docker/aissemble-spark/src/main/resources/docker/Dockerfile
- extensions/extensions-docker/aissemble-vault/src/main/resources/docker/Dockerfile
- extensions/extensions-docker/aissemble-versioning/src/main/resources/docker/Dockerfile
- extensions/extensions-docker/pom.xml
Resolves the `429 Too Many Requests - Server message: toomanyrequests: You have reached your pull rate limit` Docker Hub Error.
The following changes ensure we are using our docker credentials throughout our build process:
- Explicitly state `docker.io` repo in base images
- This allows fabric8 to pick up the registry and create a config object. Without the registry specified, fabric8 doesn't create the config object
- Update fabric8 to use own `.docker` config location
- fabric8 cleans up after its done so when using the default `.docker` config location, fabric8 removes the docker credentials. So any module that performs a pull outside of fabric8 was no longer authenticated
> 331 dockerhub rate limit - Resolve 429 Too Many Requests Error 

- extensions/extensions-helm/aissemble-spark-application-chart/values.yaml
- foundation/foundation-mda/src/main/resources/templates/deployment/spark-operator/spark-application-dev-values.yaml.vm
Specifying the Ivy user directory will override the Ivy property `ivy.default.ivy.user.dir`, which will also disallow the ivy cache to use `/home/runner/.ivy2/cache` on the runner for the local test. 
Since we only use the pod cache for the dev deployments as the we only set `storeCacheOnNode: true` for the spark-operator as part of `values-dev.yaml`, we will move the ivy cache directory to the spark application `-dev-values` file
> #363 fix the spark-application build issue

- build-parent/pom.xml
- extensions/extensions-docker/aissemble-model-training-api-containers/aissemble-model-training-api-sagemaker/src/main/resources/docker/Dockerfile
- extensions/extensions-docker/aissemble-model-training-api-containers/aissemble-model-training-api/src/main/resources/docker/Dockerfile
- extensions/extensions-docker/aissemble-versioning/src/main/resources/docker/Dockerfile
- extensions/extensions-docker/pom.xml
Update Habushu version so that python base images in Dockerfiles have fully qualified names, including the registry:
- docker.io/python:3.11
- docker.io/python:3.11-slim
Updated Modules:
- aissemble-versioning
- aissemble-model-training-api
- aissemble-model-training-api-sagemaker
> 399-dockerhub-rate-limit - update habuhsu generated code to include registry in image names

- extensions/extensions-data-delivery/aissemble-extensions-data-delivery-spark-py/src/data_delivery_spark_py/test_utils/spark_session_manager.py
- extensions/extensions-helm/aissemble-spark-application-chart/values.yaml
- foundation/foundation-mda/src/main/resources/templates/cucumber.spark.test.base.harness.java.vm
- foundation/foundation-mda/src/main/resources/templates/deployment/spark-operator/spark-application-dev-values.yaml.vm
For java 17 upgrade, we have upgraded the aissemble-spark base image, which has a different home directory than the /opt/spark/ directory so to make sure Ivy cache can find the right directory (Ivy cache is default to the environment's home directory. e.g.: ~/.ivy2), we will need to override the ivy user directory by specifying the spark.jars.ivy directory in the chart.
Currently, to fix the build issue, we have moved the `spark.jars.ivy` from the spark application chart to the dev values file to avoid the local test issue. However, since our local test is not using the docker container but only copy over the spark configuration from the yaml file to configure the spark session in the local environment, we should not copy spark.jars.ivy directory for the spark tester setup but leave it as …
> #400 overwrite ivy user directory in aissemble-spark-application-chart

- extensions/extensions-helm/aissemble-policy-decision-point-chart/README.md
- extensions/extensions-helm/aissemble-policy-decision-point-chart/templates/deployment.yaml
- extensions/extensions-helm/aissemble-policy-decision-point-chart/tests/deployment_test.yaml
- extensions/extensions-helm/aissemble-policy-decision-point-chart/values.yaml
The v2 charts for Policy Decision Point do not currently allow for the user to add an imagePullSecret so that images can be pulled from private image registries. We would like to add this functionality to the chart so that it can be used more easily in downstream projects that require the use of a private image registry.
Issue #302 https://github.com/boozallen/aissemble/issues/302
> #302 imagePullSecrets support to Policy Decision Point chart

- test/test-mda-models/test-data-delivery-spark-model-basic/pom.xml
- test/test-mda-models/test-data-delivery-spark-model/pom.xml
In ad25749d we added the extensions-messaging-kafka dependency to pipelines by default so the Kafka CDI context could be added in CdiContainerFactory. The test-mda-model projects do not regenerate their POM files on rebuild, so we need to add the new dependencies manually.
> [#391] add kafka dependency to test projects

- extensions/extensions-helm/extensions-helm-spark-infrastructure/README.md
[Original issue](https://github.com/boozallen/aissemble/issues/408)
> #408 Adjust readme for setting up new spark-infrastructure helm chart to account changes for *all* locally used values helm files

- extensions/extensions-alerting/extensions-alerting-slack/pom.xml
- extensions/extensions-alerting/extensions-alerting-slack/src/test/java/com/boozallen/aissemble/alerting/slack/CucumberTest.java
- extensions/extensions-alerting/extensions-alerting-teams/pom.xml
- foundation/foundation-alerting/pom.xml
PR is to verify the alerting modules are able to run with JDK 17. Fixed an issue with the extensions-alerting-slack module where the unit tests were not being ran on a build. Cleaned up unused dependencies and added transient dependency declarations in the pom files for the foundation-alerting, extensions-alerting, extensions-alerting-teams, and extensions-alerting-slack modules
> #359 - Modified aissemble-alerting-slack tests to run

- DRAFT_RELEASE_NOTES.md
- foundation/foundation-mda/src/main/resources/templates/data-access/data.access.pom.xml.vm
Update kafka client version in data access
>  #415 Ensure data access is compatible with JDK17

- foundation/foundation-core-java/src/main/java/com/boozallen/aissemble/core/filestore/AbstractFileStore.java
- foundation/foundation-core-java/src/main/java/com/boozallen/aissemble/core/filestore/EnvironmentVariableFileStoreConfig.java
- foundation/foundation-mda/src/main/resources/templates/file-store/file.store.impl.java.vm
#414 - JDK 17 Upgrade Support Series - Filestore & Pipeline model config
- Modifications to ensure FileStore and Pipeline model config is functional with the JDK 17 upgrade.
- Fixing an outdated aiSSEMBLE docs link in a FileStore template file.
> #414 - JDK 17 Upgrade Support Series - Filestore & Pipeline model config

- .github/workflows/build.yml
Saves the docker cache configured in the `cacheTo` and `cacheFrom` options of the Fabric8 `docker-maven-plugin` to GH caches to speed image rebuilds.  Also uses the `install-dependencies` custom action to de-duplicate the required build tool installation logic.
> [#429] add docker cache to build workflow

- foundation/foundation-upgrade/src/main/java/com/boozallen/aissemble/upgrade/migration/v1_10_0/DeltaSparkPomMigration.java
- foundation/foundation-upgrade/src/main/java/com/boozallen/aissemble/upgrade/util/YamlUtils.java
- foundation/foundation-upgrade/src/main/resources/migrations.json
- foundation/foundation-upgrade/src/test/java/com/boozallen/aissemble/upgrade/migration/utils/YamlUtilsSteps.java
- foundation/foundation-upgrade/src/test/java/com/boozallen/aissemble/upgrade/migration/v1_10_0/DeltaSparkMigration.java
- foundation/foundation-upgrade/src/test/resources/specifications/v1_10_0/delta-spark-migration.feature
- foundation/foundation-upgrade/src/test/resources/specifications/yaml-utils.feature
- foundation/foundation-upgrade/src/test/resources/test-files/v1_10_0/DeltaSparkPomMigration/migration/no-mgmt.xml
- foundation/foundation-upgrade/src/test/resources/test-files/v1_10_0/DeltaSparkPomMigration/validation/no-mgmt.xml
Also fixes a bug with the `hasDouble`, `hasInt`, and `hasBoolean` methods of `YamlObject`. Adds tests for `YamlUtils` including one to catch the root list issue. Finally, also updates the POM migration to account for POMs without dependency management sections.
> [#442] account for lists in `YamlUtils#loadYaml`

- foundation/foundation-mda/src/main/java/com/boozallen/aiops/mda/metamodel/element/java/JavaStep.java
- foundation/foundation-mda/src/main/resources/templates/data-delivery-spark/asynchronous.processor.base.java.vm
- test/test-mda-models/test-data-delivery-spark-model/src/main/resources/pipelines/SparkJavaDataDeliveryPatterns.json
We have disabled some data delivery steps as those steps are not injecting smallrye reactive messaging correctly.
It seems like any step with asynchronous type, no inbound messaging , and messaging outbound is having issue with running step execution.
Issue https://github.com/boozallen/aissemble/issues/430
> #430 FIx data delivery steps not injecting smallrye when running test-data-delivery-spark-model

- .github/workflows/build.yml
- .gitignore
- extensions/extensions-helm/aissemble-configuration-store-chart/pom.xml
- extensions/extensions-helm/aissemble-configuration-store-chart/values.yaml
- extensions/extensions-helm/aissemble-fastapi-chart/.helmignore
- extensions/extensions-helm/aissemble-fastapi-chart/pom.xml
- extensions/extensions-helm/aissemble-fastapi-chart/values-dev.yaml
- extensions/extensions-helm/aissemble-fastapi-chart/values.yaml
- extensions/extensions-helm/aissemble-quarkus-chart/.helmignore
- extensions/extensions-helm/aissemble-quarkus-chart/Chart.yaml
- extensions/extensions-helm/aissemble-quarkus-chart/pom.xml
- extensions/extensions-helm/aissemble-quarkus-chart/values.yaml
- extensions/extensions-helm/extensions-helm-spark-infrastructure/aissemble-spark-history-chart/templates/deployment.yaml
- extensions/extensions-helm/extensions-helm-spark-infrastructure/aissemble-spark-history-chart/values.yaml
- extensions/extensions-helm/extensions-helm-spark-infrastructure/aissemble-thrift-server-chart/templates/deployment.yaml
- extensions/extensions-helm/extensions-helm-spark-infrastructure/aissemble-thrift-server-chart/values.yaml
We have a pattern where we use the maven replacer plugin and a templatized `values.yaml` file to inject the project version at build time into our charts. This is the only way to provide the aissemble version as the image tag to a subchart. However, in many of the cases we've applied this pattern, the chart or the subchart is actually a custom chart made by us. This means we can simply modify the chart's template files to default the tag to the Chart version, which is set dynamically at build time.  This is greatly preferred as it's much more simple and standard Helm, and it avoids build cache issues. (E.g., if the Quarkus chart is cached, only the templatized values file exists on rebuild causing errors in charts that depend on the Quarkus chart.
> [#373] use .Chart.AppVersion for image tags in custom charts

- extensions/extensions-helm/pom.xml
- test/test-mda-models/test-data-delivery-spark-model-basic/pom.xml
- test/test-mda-models/test-data-delivery-spark-model/pom.xml
Using the `.Chart.AppVersion` for image tags exposed a bug that was introduced when we moved to opensource.  Previously we were overwriting path dependencies in helm charts during the release process via the `release` profile. After open-sourcing our release profile name changed from `release` to `ossrh-release`, but we didn't update it in the `extensions-helm` POM.  However, it was incorrect to only rewrite dependencies during release anyway, as the chart dependencies should be rewritten _any_ time we're deploying (including snapshots). So instead we moved the functionality to the `ci` profile (which is also active during release.)
Also found an issue with release-prepare introduced by #451 preventing the version update process due to unresolved property.
> [#373] fix chart deployment

- .github/workflows/build.yml
- devops/ARC_README.md
- devops/arc-runner-service-account.yaml
- devops/clusterrole-configmap-manager-default.yml
- devops/clusterrole-configmap-manager.yml
- devops/controller-values.yaml
- devops/helm-it-user.yml
- devops/runnerset-values.yaml
- extensions/extensions-helm/pom.xml
The documentation for setting up self-hosted runners that can handle the aissemble build via the Actions Runner Controller project has been added to `devops`. In addition, the `helm install --dry-run` IT has been removed and the build action has been adjusted to skip cache-restore actions if the trigger was a schedule.  The dry run was removed largely because it just requires too many permissions to function and isn't adding much more than our strict linting operation and unit tests. The cache restore skip was added as an alternative to the manual cache deletion logic we were doing in the build before. General cache cleanup is handled automatically by S3.
> [#467] document self-hosted runner setup

- cucumber-report-aggregator/pom.xml
- pom.xml
#447 Generate aggregated Cucumber report
Replaces the plugin that was used in Jenkins that would aggregate all individual Cucumber reports into one. The focus of this commit will be to generate an aggregated cucumber report of ALL the tests within aiSSEMBLE.
> #447 Generate aggregated Cucumber report

- test/test-mda-models/aissemble-test-data-delivery-pyspark-model/tests/features/pyspark_data_encryption.feature
- test/test-mda-models/aissemble-test-data-delivery-pyspark-model/tests/features/pyspark_data_encryption_vault.feature
- test/test-mda-models/aissemble-test-data-delivery-pyspark-model/tests/features/steps/pyspark_data_encryption_steps.py
Part of the encryption IT scenarios were checking that the right number of fields were retrieved by the `get_field_list` method.  I'm not sure that this makes sense as an encryption test.  Either the encryption method (which uses `get_field_list`) encrypts fields correctly, or it doesn't. I don't see a ton of value in testing that method specifically over the actual encryption tests which indirectly test `get_field_list`.
This changeset also splits off the vault scenarios into a separate feature, as those are the only real "IT" scenarios.  We can't just tag the scenarios directly because the feature-level tag is used to determine whether we should stand up the Vault image, and we can't base this logic at the scenario level because that would tear down and deploy Vault between each …
> [#469] fix encryption ITs for changed MDA model
